env: standard
runtime: python27
threadsafe: true
service: thorchain

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always